### ISSUE TITLE
[Issue] License mismatch

### ISSUE THREAD

**Issue by Legorobotdude** [dwhickox/ILLINI-Lights#2]
The licesnse.md is cc-by-nc-sa but in the header of the code it states that it is released under the GPLv3 license by Shae Erisson.

**Comment by dwhickox** [comment]
It displays no header for me but this may be a GitHub issue as I can't change headers on my other licenses, the correct license is the creative commons non commercial share alike

**Comment by Legorobotdude** [comment]
Sorry, I meant in the actual header comments. See lines 3-4 in ILLINI-Multi-Letter.ino
